//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooWork.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingWithAnimals
    {
        public int ID { get; set; }
        public Nullable<int> idEmployees { get; set; }
        public Nullable<int> idAnimals { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
